### ISSUE TITLE
Too long send Latency

### ISSUE THREAD

**Issue by chiwangnvp** [alvr-org/ALVR#731] opened 2021-07-13 07:22 UTC
Hello we're using ALVR on our own VR platform, but recently we have found out a problem that the "sendLatency": 101.129, that's too long, isn't it? We haven't modify any code about the Network part of the ALVR, why it take such a long time?

The detailed latency Log in the attachment：
[测试机延时log.txt](https://github.com/alvr-org/ALVR/files/6806675/log.txt)

**Comment by chiwangnvp** [comment] 2021-07-13 11:36
**"receiveLatency": 4294935.863**, "renderTime": 18.065, "idleTime": 0.302, "waitTime": 12.683, "encodeLatency": 4.993, **"sendLatency": 3.129**

**Comment by xytovl** [comment] 2021-07-13 11:46
You may not be using the latest version, there have been some improvements on latency reporting.

Such a high latency seems to be an issue on client part: either network is saturated or the headset can't keep up.

Also it would be very nice if you could share your code, so it benefits both projects.

**Comment by chiwangnvp** [comment] 2021-07-14 09:58
Hi xytovl，
    
Thank you for your reply!

As bellow is our ：
1. our version is **commit 898b9153cf2aa5ef93732286689126843d2c8926**( Date:   Tue Jun 29 19:43:54 2021 -0500 ), this may not be the newest, but I think it will work fine, does it?
2. we test our network using the tool called iperf on our Hmd, you could see the upload img D1_iperf_result.png. And our conclusion is our network bandwidth is good : the need of transmitting video flow bandwidth is about 4320 * 2160 * 24 * 30 / 250(H264 compression ratio?) = 25.6Mbps(right here?) and our network bandwidth is about 300Mbps.
<img width="543" alt="D1_iperf_result" src="https://user-images.githubusercontent.com/45933755/125595796-1b568aef-2fc6-46c0-8c37-aeac2358334e.png">
3. what do you mean about "**the headset can't keep up**"? Do you mean the sendTrackingInfo on our client side is blocked the following up transmition, so here comes the "receiveLatency": 4294935.863 which I mentioned before?
4. about our code, we're organizing it right now, and we just adapted the alvr client side on our device, here is part of our change list :
        modified:   alvr/client/android/app/CMakeLists.txt
        modified:   alvr/client/android/app/include/VrApi.h
        modified:   alvr/client/android/app/include/VrApi_Config.h
        modified:   alvr/client/android/app/include/VrApi_Helpers.h
        modified:   alvr/client/android/app/include/VrApi_Input.h
        modified:   alvr/client/android/app/include/VrApi_SystemUtils.h
        modified:   alvr/client/android/app/include/VrApi_Types.h
        modified:   alvr/client/android/app/include/VrApi_Version.h
        modified:   alvr/client/android/app/src/main/cpp/ServerConnectionNative.cpp
        modified:   alvr/client/android/app/src/main/cpp/ffr.h
        modified:   alvr/client/android/app/src/main/cpp/gltf_model.cpp
        modified:   alvr/client/android/app/src/main/cpp/gltf_model.h
        modified:   alvr/client/android/app/src/main/cpp/nal.cpp
        modified:   alvr/client/android/app/src/main/cpp/ovr_context.cpp
        modified:   alvr/client/android/app/src/main/cpp/render.cpp
        modified:   alvr/client/android/app/src/main/cpp/render.h
        modified:   alvr/client/android/app/src/main/java/com/polygraphene/alvr/DecoderThr
ead.java
        modified:   alvr/client/android/app/src/main/java/com/polygraphene/alvr/OvrActivit
y.java

Thank you for your support

**Comment by ckiee** [comment] 2021-07-18 15:09
Maybe you could try rebasing your changes on top of https://github.com/alvr-org/ALVR/commit/53293316? We recently merged adaptive bitrate so maybe the problem is related to that.

**Comment by chiwangnvp** [comment] 2021-07-19 11:51
We found the reason why such a high latency is that : the send Tracking Info thread might be run too slow, it leads to every 400ms  latency after which it sends the info of hmd info again, so xytovl is right that **network is saturated or the headset can't keep up**.

**Comment by chiwangnvp** [comment] 2021-07-19 11:53
We boost our cpu frequencies in XR2, it will relieve the latency.

**Closed** 2021-07-19 11:53 UTC
