### ISSUE TITLE
Can't  get VR headset to display something, even after following the Linux Troubleshoot

### ISSUE THREAD

**Issue by Alerk09** [alvr-org/ALVR#2506] opened 2024-11-12 20:53 UTC
## Description
I followed the Linux Troubleshoot first step and it still doesnt display, but got this:
21:47:28.027 ERROR Encoder: Image creation failure: Unknown error
21:47:28.034 ERROR error in encoder thread: Failed to initialize vulkan frame context: Invalid argument

## General Troubleshooting
- [ ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload` https://linux-hardware.org/?probe=e3de54db8d

**CPU**: Intel Core i5 1135g7

**GPU**: Intel Iris Xe 

**GPU Driver Version**: i915, xe

**Audio**: pipewire

### Installation
**ALVR Version**: 20.11.1

**ALVR Settings File**:

**SteamVR Version**: 2.8.6

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source
- [x] ALVR Launcher

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux

**Comment by The-personified-devil** [comment] 2024-11-13 17:05
This is a duplicate of #2014, it's gonna get fixed at some point but can't promise when

**Closed by The-personified-devil** 2024-11-13 17:05 UTC
