### ISSUE TITLE
Pico 4 Support

### ISSUE THREAD

**Issue by phr00t** [alvr-org/ALVR#1206] opened 2022-10-13 19:35 UTC
Pico 4 is coming out, which has a very similar setup as the Quest 2 (e.g. Android device that requires USB or Wifi streaming to play PCVR games). So far, reports of the included Pico Streaming Assistant software is lacking, making tools like Virtual Desktop and ALVR very important. I didn't see anything referencing the Pico 4 yet on this Github page, so I make an issue to kick this off.

I've got a Pico 4 coming sometime around the end of next week and may be willing to help here. I'm hoping that much of whats been done with Quest 2 support will easily translate to the Pico 4, which uses the same chipset.

**Comment by korejan** [comment] 2022-10-13 19:39
@phr00t [ALXR](https://github.com/korejan/ALVR/wiki/ALXR-Client) runs on Pico 4

**Comment by phr00t** [comment] 2022-10-13 20:06
@korejan oh awesome! I'll follow you there :-)

**Comment by MartinPL** [comment] 2022-11-16 14:39
This project don't work with Pico 4 so issue should be open.

**Comment by zarik5** [comment] 2022-11-16 18:13
I agree the issue should be open, as the request is legitimate, but ALVR will likely not support Pico headsets until their SDK respects the OpenXR spec.

**Comment by BobbyMcJefferson** [comment] 2022-12-10 15:37
Now that Virtual Desktop officially killed LAN support by making an internet connection mandatory, we need an open-source solution more than ever. Especially on the Pico 4 where the native streaming assistant just sucks.

**Comment by galister** [comment] 2022-12-14 16:15
What exactly is missing from their OpenXR implementation? Asking so that we can make our voices heard on their channels.

**Comment by zarik5** [comment] 2022-12-14 16:27
@galister The problem is that their OpenXR SDK requires some private extensions that change the tracking/render/display flow in a way that makes it incompatible with streaming applications and in general all applications that have a latency between tracking poll and frame display greater than `1/refresh rate`. I don't quite remember the name of these extensions. From what I know, Pico has no plan to change this in the near future.

**Comment by BobbyMcJefferson** [comment] 2022-12-21 19:12
Just a heads up for anyone who stopped using VD. They basically restored the offline functionality. DRM check only has to be done once per update, and you need internet to get the update anyway. Still would be nice to have ALVR as an option of course but now at least VD offline users aren't screwed anymore.

**Comment by zarik5** [comment] 2023-02-02 09:52
OpenXR has merged and Pico 4 support is present.

**Closed** 2023-02-02 09:52 UTC
Labels: enhancement
