### ISSUE TITLE
Valve Index Headset emulation

### ISSUE THREAD

**Issue by TAGMONKE** [alvr-org/ALVR#2294] opened 2024-07-28 16:23 UTC
please add this. i beg

**Comment by The-personified-devil** [comment] 2024-07-30 12:26
Why exactly do you need this? The more the emulated headset differs from the real headset the buggier it gets

**Comment by zarik5** [comment] 2024-07-30 15:56
I assume the main reason is the discrepancy between emulated headset and emulated controllers for the tracking space name, which is a OpenVR property. if the tracking name differs then any kind of recentering, triggered manually or by the game, head and controllers will uncalibrate. The solution would be to invent some strings for the valve index headset, then unify the emulation selection for head and controllers, so they get selected in lockstep.

**Comment by TAGMONKE** [comment] 2024-08-01 19:58
> I assume the main reason is the discrepancy between emulated headset and emulated controllers for the tracking space name, which is a OpenVR property. if the tracking name differs then any kind of recentering, triggered manually or by the game, head and controllers will uncalibrate. The fix i've been recomending is to change the tracking name using the extra props list but it's quite hidden. The solution would be to invent some strings for the valve index headset, then unify the emulation selection for head and controllers, so they get selected in lockstep.

Nice idea

**Comment by zarik5** [comment] 2024-09-08 19:45
Closing as duplicate of #262

**Closed by zarik5** 2024-09-08 19:45 UTC
Labels: enhancement
