### ISSUE TITLE
Indefinite Client-side load screen

### ISSUE THREAD

**Issue by FoxbitDreamtail** [alvr-org/ALVR#2267] opened 2024-07-20 03:55 UTC
## Description
this is a recent regression in the Quest 2 Client app, on successful connection the quest display will indefinitely load.

The last version that worked was `v21.0.0-dev01+nightly.2024.07.17`.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: 11th Gen Intel i5-11400F

**GPU**: AMD ATI Radeon RX 6800

**GPU Driver Version**: 4.6 Mesa 24.1.4 - kisak-mesa PPA

**Audio**: Alsa + Pipewire v1.0.7

### Installation
**ALVR Version**: v21.0.0-dev01+nightly.2024.07.19

**ALVR Settings File**: stock(except refresh rate is changed from 72hz -> 90hz)

**SteamVR Version**: 2.6.2(latest stable as of writing)

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Linux Mint 21.3

**Comment by The-personified-devil** [comment] 2024-07-20 11:27
Can you post streamer logs (there's an option in the settings to log to a file) and also post whatever `adb logcat | grep "ALVR NATIVE-RUST"` outputs, so we can get some client logs?

**Comment by FoxbitDreamtail** [comment] 2024-07-20 16:17
this is the output...
`07-20 11:14:52.097  6478  6510 W [ALVR NATIVE-RUST]: EGL_MESA_platform_surfaceless not available. Using default platform
07-20 11:14:52.104  6478  6510 W [ALVR NATIVE-RUST]: EGL says it can present to the window but not natively
07-20 11:14:52.138  6478  6510 I [ALVR NATIVE-RUST]: Adapter Gl AdapterInfo { name: "Adreno (TM) 650", vendor: 20803, device: 0, device_type: IntegratedGpu, driver: "OpenGL ES", driver_info: "3.2 V@0767.0 (GIT@b96f8a4bfa, Iad89979a5b, 1709780503) (Date:03/06/24)", backend: Gl }
07-20 11:14:53.388  6478  6584 I [ALVR NATIVE-RUST]: Initial socket buffer size: send: 524288B, recv: 1048576B
07-20 11:15:16.386  6478  6584 I [ALVR NATIVE-RUST]: Server restarting
07-20 11:15:17.388  6478  6584 I [ALVR NATIVE-RUST]: Initial socket buffer size: send: 524288B, recv: 1048576B
07-20 11:15:19.581  6478  6584 I [ALVR NATIVE-RUST]: Stream starting
07-20 11:15:19.582  6478  6584 I [ALVR NATIVE-RUST]: Initial socket buffer size: send: 212992B, recv: 212992B
07-20 11:15:19.583  6478  6584 I [ALVR NATIVE-RUST]: Set socket send buffer succeeded: 16777216
07-20 11:15:19.583  6478  6584 I [ALVR NATIVE-RUST]: Set socket recv buffer succeeded: 16777216
07-20 11:15:19.583  6478  6584 I [ALVR NATIVE-RUST]: Connected to server
07-20 11:15:19.597  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.613  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.623  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.634  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.644  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.654  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.665  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.677  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.688  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.698  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.710  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.721  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.732  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.747  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.764  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.777  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.789  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.798  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.808  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.824  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.833  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.844  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.857  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.866  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.881  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.892  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.901  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.912  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.922  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.932  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.943  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.956  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.965  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.975  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.987  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:19.997  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.008  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.019  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.030  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.041  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.052  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.062  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.072  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.085  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.096  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:20.107  6478  6737 E [ALVR NATIVE-RUST]: Audio record error: Internal
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]: ALVR panicked: What happened:
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]: panicked at alvr/client_core/src/graphics/mod.rs:112:46:
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]: called `Option::unwrap()` on a `None` value
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]: 
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]: Backtrace:
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    0: alvr_common::logging::set_panic_hook::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/common/src/logging.rs:47:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2036:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::panicking::rust_panic_with_hook
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:799:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    2: std::panicking::begin_panic_handler::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:656:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:171:18
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    4: rust_begin_unwind
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    5: core::panicking::panic_fmt
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    6: core::panicking::panic
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:146:5
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    7: core::option::unwrap_failed
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:1984:5
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    8: wgpu_core::resource::<impl wgpu_core::global::Global>::device_as_hal
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       wgpu::backend::wgpu_core::ContextWgpuCore::device_as_hal
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/backend/wgpu_core.rs:193:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       wgpu::Device::as_hal::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/lib.rs:2920:21
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       core::option::Option<T>::map
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/option.rs:1072:29
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       wgpu::Device::as_hal
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.20.1/src/lib.rs:2919:14
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       alvr_client_core::graphics::create_texture_from_gles
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_core/src/graphics/mod.rs:109:27
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:    9: alvr_client_core::graphics::create_gl_swapchain::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_core/src/graphics/mod.rs:153:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       core::iter::adapters::map::map_fold::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/adapters/map.rs:89:28
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::fold
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/slice/iter/macros.rs:230:27
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/adapters/map.rs:129:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       core::iter::traits::iterator::Iterator::for_each
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/traits/iterator.rs:818:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       alloc::vec::Vec<T,A>::extend_trusted
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:3098:17
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_extend.rs:26:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/spec_from_iter.rs:33:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   10: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/vec/mod.rs:2972:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       core::iter::traits::iterator::Iterator::collect
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/iter/traits/iterator.rs:2004:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       alvr_client_core::graphics::create_gl_swapchain
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_core/src/graphics/mod.rs:155:10
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       alvr_client_core::graphics::lobby::LobbyRenderer::new
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_core/src/graphics/lobby.rs:220:13
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   11: alvr_client_openxr::lobby::Lobby::new
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_openxr/src/lobby.rs:46:24
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       alvr_client_openxr::entry_point
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_openxr/src/lib.rs:255:25
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   12: alvr_client_openxr::android_main::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /home/runner/work/ALVR-nightly/ALVR-nightly/alvr/client_openxr/src/lib.rs:494:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::sys_common::backtrace::__rust_begin_short_backtrace
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys_common/backtrace.rs:155:18
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   13: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:542:17
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panic/unwind_safe.rs:272:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::panicking::try::do_call
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:559:40
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::panicking::try
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:523:19
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::panic::catch_unwind
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panic.rs:149:14
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::thread::Builder::spawn_unchecked_::{{closure}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/mod.rs:541:30
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       core::ops::function::FnOnce::call_once{{vtable.shim}}
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/alloc/src/boxed.rs:2022:9
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:       std::sys::pal::unix::thread::Thread::new::thread_start
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:              at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/sys/pal/unix/thread.rs:108:17
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   15: _ZL15__pthread_startPv
07-20 11:15:22.832  6478  6510 E [ALVR NATIVE-RUST]:   16: __start_thread`

**Comment by The-personified-devil** [comment] 2024-07-20 17:02
Somehow the formatting breaks with github so I fixed it up
[client.log](https://github.com/user-attachments/files/16321762/client.log)

As for streamer logging in the alvr dashboard there's a setting under Extras->Logging to enable log to disk which will log to a file called `alvr_session_log.txt` in your home directory that you can simply upload, which is the most convenient option. Though I think we don't need the streamer logs seeing as everything important seems to be caught by the client logs

**Comment by The-personified-devil** [comment] 2024-07-20 17:15
So the issue seems to be that the device is created with the wrong backend causing the closure at https://github.com/alvr-org/ALVR/blob/master/alvr/client_core/src/graphics/mod.rs#L111 to be fed a `None`, tho I'm not sure why the backend would be wrong considering the logs say that the adapter is using the gl backend, which means gles.

**Comment by FoxbitDreamtail** [comment] 2024-07-20 17:39
maybe compare the files from `v21.0.0-dev01+nightly.2024.07.17`(Last known good) to `v21.0.0-dev01+nightly.2024.07.19`(latest) and see what changed?

**Comment by The-personified-devil** [comment] 2024-07-20 17:45
@FoxbitDreamtail That won't work because a good chunk of code was rewritten between those nightlies and the bug is entirely contained in the rewritten code

**Comment by The-personified-devil** [comment] 2024-07-20 17:52
Could you upload your alvr configuration however? That would be a great help to make it easier to reproduce the failure. It should be `~/.config/alvr/session.json`.

**Comment by FoxbitDreamtail** [comment] 2024-07-20 19:40
> @FoxbitDreamtail That won't work because a good chunk of code was rewritten between those nightlies and the bug is entirely contained in the rewritten code

If it wasn't broken, why was it fixed?

**Comment by Vixea** [comment] 2024-07-20 19:47
It was broken, the old code was written in c++ but the build system used by SandboxVR doesn't allow that code to be built using the newer build system that was merged ages ago. So the code needs to be written in rust which is what we are currently doing.

**Comment by FoxbitDreamtail** [comment] 2024-07-20 19:49
ah, So you couldn't have taken it and put it into a C++ to Rust converter and then worked from there? There are converters for hundreds of different coding languages out there... So why not use that and just easily be able to convert it? Or am I missing something plain and obvious?

**Comment by The-personified-devil** [comment] 2024-07-20 19:54
Because that doesn't give any of the advantages of rust. That's what zarik initially did (pretty much repeating the c++ code in rust (way less janky than using an automatic converter)), but actually writing idiomatic rust code was also a goal, so the switch to wgpu was performed, which is apparently kinda broken.

**Comment by FoxbitDreamtail** [comment] 2024-07-20 23:34
> Because that doesn't give any of the advantages of rust. That's what zarik initially did (pretty much repeating the c++ code in rust (way less janky than using an automatic converter)), but actually writing idiomatic rust code was also a goal, so the switch to wgpu was performed, which is apparently kinda broken.

so, what you're saying is to just stick with `v21.0.0-dev01+nightly.2024.07.17` until it breaks or until this issue is resolved?

**Comment by Meister1593** [comment] 2024-07-20 23:53
better question is, why sticking to nighties if not for testing specifically (by now)? (they are kind of expected to be with issues, mostly untested)

**Closed** 2024-07-21 21:59 UTC

**Comment by FoxbitDreamtail** [comment] 2024-07-21 23:11
> better question is, why sticking to nighties if not for testing specifically (by now)? (they are kind of expected to be with issues, mostly untested)

Features which are not in release. I am on Linux, not Windows.

**Comment by The-personified-devil** [comment] 2024-07-21 23:24
Curious as to what features that actually are since pipewire support is in stable

**Comment by FoxbitDreamtail** [comment] 2024-07-22 15:38
> Curious as to what features that actually are since pipewire support is in stable

All audio to and from the quest does not function in stable, Also, when in the quest client you cannot see the position of the quest controllers or hand tracking, And finally, there are optimization problems whenever it comes to streaming.

**Comment by Vixea** [comment] 2024-07-22 15:43
Have you made sure to delete the on connect, on disconnect scripts?

**Comment by FoxbitDreamtail** [comment] 2024-08-12 22:13
> Have you made sure to delete the on connect, on disconnect scripts?

I should have clearified, sorry, I am on linux Mint XFCE 21.3(Upgrade not pushed yet) I prefer stability over the latest features but "stable" is not stable for me. SteamVR is the primary reason I use nightlies. if I didn't need to use SteamVR, then I wouldn't be using a nightly build.
