### ISSUE TITLE
Unreal Engine 4/5 VR preview crashes when using OpenXR

### ISSUE THREAD

**Issue by officialnochill** [alvr-org/ALVR#1392] opened 2023-01-20 16:33 UTC
Applies to ALVR versions tested (v18.2.3, v19)

## Description
Been having this issue with ALVR for over a year.

![image](https://user-images.githubusercontent.com/63358288/213752301-38e1a62c-1bf5-4e69-bbd7-34fccbec41c6.png)

The depreceated SteamVR plugin works
To reproduce you pretty much just load the default Unreal 5.1 VR (applies to UE4 as well) template and open the VR preview.

Here it is running fine when you don't use the OpenXR plugin:
![image](https://user-images.githubusercontent.com/63358288/213752516-127c6dbb-d1c8-406f-8bea-59108e67c6c0.png)

The closest you can get it to not crashing is this:

![image](https://user-images.githubusercontent.com/63358288/213752596-ec85846c-b659-4d8d-86dd-f3fded0b4df0.png)
where it still doesn't display in SteamVR or the headset but at least it does not crash.

Airlink/Oculus Link works fine

## General Troubleshooting
Resetting and resintalling all ALVR settings multiple times.

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**:
Ryzen 3100

**GPU**:
GTX 1060

### Installation
**ALVR Version**: v18.2.3, v19

**SteamVR Version**: 1.25.3

**Install Type**:
Multiple installs in different folders

**OS Name and Version**):
Windows 11 22H2

**Comment by zarik5** [comment] 2023-03-12 20:46
Sorry, this should not be closed.

**Comment by rkazakoff** [comment] 2023-03-23 13:38
Similar issue with UE5 games. No idea how to fix.
ALVR Version: v19, v19.1
SteamVR: v1.25.6
CPU: Ryzen 5600x
GPU: rx6750xt

**Comment by RGAA-Software** [comment] 2023-04-10 08:03
also crashed steamVR.
UE5.1 apps.
I have tried v20.0 beta that i compiled myself, but has no effect.
CPU: intel i9
GPU: RTX 3060

**Comment by RGAA-Software** [comment] 2023-04-13 08:41
Maybe something mismatch, i find some error , for example, in OvrHmd.cpp, the method : vr::VRSettings(), return nullptr.

**Comment by TandyTnd** [comment] 2023-04-22 05:52
It seems to affect all unreal engine games using openxr.

**Comment by zarik5** [comment] 2023-04-22 07:14
Is this reproducible on Linux?

**Comment by MonkeyMayham** [comment] 2023-05-07 01:13
any fix on this?

**Comment by TandyTnd** [comment] 2023-05-07 04:56
This is the log generated when trying to launch ghosts of tabor (unreal openxr game).  Not sure of this means exactly. 

Sat May 06 2023 22:07:05.392 - Capturing Scene Focus
Sat May 06 2023 22:07:05.408 - GetHiddenAreaMeshData: no hidden area mesh data available
Sat May 06 2023 22:07:05.408 - GetHiddenAreaMeshData: no hidden area mesh data available
Sat May 06 2023 22:07:05.432 - Found Windows 10 or newer, so enable advanced image processing of scene textures.
Sat May 06 2023 22:07:05.457 - Setting max texture dimensions to 1282x1442 before requiring downsampling
Sat May 06 2023 22:07:10.459 - Closing pipe VR_ServerPipe_37168 because it was broken from the other end
Sat May 06 2023 22:07:10.459 - Timeout while waiting for message of type 901 on pipe VR_ServerPipe_37168
Sat May 06 2023 22:07:10.459 - Purging all shared textures because the connection to vrserver was lost
Sat May 06 2023 22:07:10.459 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.459 - ComposeLayerProjection: failed to submit view 0: VRCompositorError_TextureUsesUnsupportedFormat
Sat May 06 2023 22:07:10.459 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.459 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.459 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.459 - ComposeLayerProjection: failed to submit view 1: VRCompositorError_TextureUsesUnsupportedFormat
Sat May 06 2023 22:07:10.459 - Transitioning XrSession from XR_SESSION_STATE_READY to XR_SESSION_STATE_SYNCHRONIZED
Sat May 06 2023 22:07:10.459 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.459 - Transitioning XrSession from XR_SESSION_STATE_SYNCHRONIZED to XR_SESSION_STATE_VISIBLE
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_VISIBLE to XR_SESSION_STATE_FOCUSED
Sat May 06 2023 22:07:10.532 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.532 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.532 - Lost connection to VR Server
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_FOCUSED to XR_SESSION_STATE_VISIBLE
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_VISIBLE to XR_SESSION_STATE_SYNCHRONIZED
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_SYNCHRONIZED to XR_SESSION_STATE_STOPPING
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_STOPPING to XR_SESSION_STATE_IDLE
Sat May 06 2023 22:07:10.532 - Transitioning XrSession from XR_SESSION_STATE_IDLE to XR_SESSION_STATE_EXITING
Sat May 06 2023 22:07:10.532 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.532 - Changing app type from VRApplication_OpenXRScene to VRApplication_OpenXRInstance
Sat May 06 2023 22:07:10.532 - WaitNamedPipe VR_ServerPipe_37168 failed because no one is listening at that name.
Sat May 06 2023 22:07:10.532 - IPC failure changing app type
Sat May 06 2023 22:07:10.532 - Unexpected error while trying to change the OpenXR application type: [VRInitError_Init_Internal]

**Comment by cloudending** [comment] 2023-05-16 05:11
I found crash in CreateSwapTextureSet. because the texure format is DXGI_FORMAT_R32G8X24_TYPELESS. This will cause a failure when calling CreateTexture2D. I try to skip this texture creation. it won't crash. But there is a problem that the frame jitters when I used unreal openxr plugin. Instead of using steamvr plugin, frame jitter is gone.

**Comment by zarik5** [comment] 2023-05-22 00:59
@cloudending Thanks for the finding. I didn't forget about this bug but i have many other things to worry about at the moment. Maybe some other people can help with this issue.

**Comment by Vixea** [comment] 2023-06-17 16:51
I'll close this issue as it should be fixed, if the author doesn't reply after awhile.

**Comment by TandyTnd** [comment] 2023-06-17 19:43
I tested it, all unreal engine openxr games work now.

**Closed** 2023-06-17 21:22 UTC
Labels: bug
