### ISSUE TITLE
Launcher v20.10 cannot download nightlies

### ISSUE THREAD

**Issue by failboat78** [alvr-org/ALVR#2379] opened 2024-09-08 18:50 UTC
As subject. Older version did allow nightly downloads. 

Same behavior on both windows and linux. Dropdown box won't let you pick "nightly".

This is a bug right?

bad launcher - https://github.com/alvr-org/ALVR/releases/tag/v20.10.0
good launcher - https://github.com/alvr-org/ALVR/releases/tag/v20.9.1

**Comment by zarik5** [comment] 2024-09-08 19:34
lready fixed in nightly launcher

**Closed by zarik5** 2024-09-08 19:34 UTC

**Comment by The-personified-devil** [comment] 2024-09-08 19:57
Duplicate of #2377 and #2362 btw

**Comment by failboat78** [comment] 2024-09-08 20:17
Damnit I even searched for dups >.<
