### ISSUE TITLE
Disable hand tracking when using gamepad

### ISSUE THREAD

**Issue by zarik5** [alvr-org/ALVR#127] opened 2020-02-26 18:52 UTC
Currently, with Oculus Mobile SDK v13, if the hand tracking capability is set in AndroidManifest.xml, it seems there isn't a way to disable hand tracking when the controllers are inactive.
If you want to use a gamepad, with ALVR you can disable the controllers input, but if the controllers are inactive, hand tracking is activated and when it glitches and one hand flies away, the guardian boundary pops up, and this can be distracting.

**Comment by JackD83** [comment] 2020-02-29 11:20
You mean an option like "allow only controller input"? I also noticed that if the quest switches to hand tracking and one or both hands are not tracked, they move to position 0,0 which is right in your face

**Comment by zarik5** [comment] 2020-02-29 11:46
No, that is another problem. Even if controller/hand tracking input is ignored in the client, the guardian boundary still pops up when hands exit the play area. A workaround is to disable guardian boundary in Oculus Quest settings.

This is a limitation of the SDK so no action can be taken now. I opened this issue just as a reminder for when a future SDK update will allow this to be fixed.

**Comment by ronthecookie** [comment] 2021-05-17 18:51
Duplicate of #255.

**Closed by ronthecookie** 2021-05-17 18:51 UTC
Labels: unactionable
