### ISSUE TITLE
20.1 super high GPU usage on idle

### ISSUE THREAD

**Issue by dumbpinoob** [alvr-org/ALVR#1716] opened 2023-06-30 15:37 UTC
## Description
My GPU draws it's full 200W and sits at full utilization when I open steamvr, it stays the same when launching a game and its horribly laggy. It worked fine with the same drivers on ALVR 18.2. Updating to 20.1 caused this along with reverting all my settings.

**CPU**: 12400f

**GPU**: 6700xt

**GPU Driver Version**: 23.5.2

**Audio**: quest 2 speakers

### Installation
**ALVR Version**: 20.1.0

**ALVR Settings File**: ?

**SteamVR Version**: 1.25.8

Windows 11 22H2

**Comment by Vixea** [comment] 2023-06-30 15:39
Duplicate of #1714

**Comment by Vixea** [comment] 2023-06-30 15:41
Please comment with this on the original issue

**Closed** 2023-06-30 15:40 UTC
