### ISSUE TITLE
ALVR Driver not being loaded

### ISSUE THREAD

**Issue by Equinoxx4978** [alvr-org/ALVR#2131] opened 2024-05-16 08:26 UTC
I've installed ALVR and got it all configured.
When I clicked lauch SteamVR, it opened as expected, however the ALVR driver wasn't being loaded.
The entry for ALVR was not located in the SteamVR settings add-ons page.

I looked in the ALVR app and it said the driver was located in `/usr/lib/steamvr/alvr/` however when I opened SteamVR's files I saw that all my driver were stored in `~/.local/share/Steam/steamapps/common/SteamVR`.
When I moved the file from `/usr/....` to `/home/Josh/.local/share/Steam/steamapps/common/SteamVR/drivers` the driver did appear within SteamVR, but the streamer still wouldn't connect within ALVR.

The reason (im guessing) that ALVR isnt able to connect to the streamer was because its driver was never being loaded because it's in the incorrect location and has things set out incorrectly.

For context (in needed) I'm running:
- Arch Linux
- AMD Radeon RX 6700XT
- Wayland
- Gnome 46

Any help is appreciated as I would really like to use my Quest 3 for PCVR without windows :)

**Comment by josbraden** [comment] 2024-05-16 15:46
Ah a fellow Josh, is this a duplicate of #2130?

**Comment by sithlord48** [comment] 2024-05-17 01:27
I have this same issue.  
SteamVR just does not list the driver in the list of drivers. I doesn't matter if I use SteamVR 2.5.5 or the previous from the beta list. 

I have removed my config files as well as reinstalled alvr and steam vr (a few times)

**Comment by Equinoxx4978** [comment] 2024-05-17 07:17
@32bitx64bit ill try out a different DE and ill see how it goes. also will try x11 too just in case

**Comment by Equinoxx4978** [comment] 2024-05-17 10:53
I've tried X11 and it's still not working.

I still get the issue of the streamer not connecting.
Driver also does not appear in steamvr like before.

![image](https://github.com/alvr-org/ALVR/assets/89617359/86eef798-6501-4721-b000-2355462949a1)

**Comment by sithlord48** [comment] 2024-05-17 12:55
This is not a Gnome specific issue. I'm use KDE and tried both X11 and Wayland.

**Comment by 32bitx64bit** [comment] 2024-05-19 03:09
> @32bitx64bit ill try out a different DE and ill see how it goes. also will try x11 too just in case

Hm. Odd. Can confirm it just randomly stopped working for me, even on the previous version, No idea what ALVR did, but they fucked something up.

**Comment by 32bitx64bit** [comment] 2024-05-20 11:13
Found a solution, trying right now.

**Comment by 32bitx64bit** [comment] 2024-05-20 11:26
Ok so, it seems for some reason at least for my system instead of using the AUR package for ALVR, just downloading the tar file, and extracting it, fixes the drvier not loading.

**Comment by Equinoxx4978** [comment] 2024-05-20 11:28
> Ok so, it seems for some reason at least for my system instead of using the AUR package for ALVR, just downloading the tar file, and extracting it, fixes the drvier not loading.

I'll give this a go

**Comment by Equinoxx4978** [comment] 2024-05-20 11:48
Driver loads, but crashes because of
`21:47:05.467632542 ERROR Handshake error for 9643.client: Cannot find audio device which name contains "pipewire"`
Then because of the crash the driver gets auto-disabled.
Any help?

**Comment by sithlord48** [comment] 2024-05-20 14:09
I can see it when i use the tarball deployment however I also get that handshake error.

I was able to get it to connect if I disabled both the game audio and microphone but then i only was able to see a black screen on my headset.

**Comment by 32bitx64bit** [comment] 2024-05-20 16:47
> Driver loads, but crashes because of `21:47:05.467632542 ERROR Handshake error for 9643.client: Cannot find audio device which name contains "pipewire"` Then because of the crash the driver gets auto-disabled. Any help?

If you're still on gnome wayland, gnome wayland does **NOT** support DRM (Direct Rendering Manager) on wayland.

If this isn't the case revert to the "Previous" version of steamVR.

**Comment by sithlord48** [comment] 2024-05-20 18:13
I am not on Gnome wayland issue, as i see the same issue with the pipewire device.

> I can see it when i use the tarball deployment however I also get that handshake error.
> I was able to get it to connect if I disabled both the game audio and microphone but then i only was able to see a black screen on my headset.

**Comment by Equinoxx4978** [comment] 2024-05-21 07:55
> If you're still on gnome wayland, gnome wayland does **NOT** support DRM (Direct Rendering Manager) on wayland.
> 
> If this isn't the case revert to the "Previous" version of steamVR, as the driver does not currently support latest steamVR version(s)

I was on xorg at the time, i believe this may be due to something else...

**Comment by 32bitx64bit** [comment] 2024-05-21 15:24
> > If you're still on gnome wayland, gnome wayland does **NOT** support DRM (Direct Rendering Manager) on wayland.
> > If this isn't the case revert to the "Previous" version of steamVR, as the driver does not currently support latest steamVR version(s)
> 
> I was on xorg at the time, i believe this may be due to something else...

Might just be a driver issue with ALVR then, and or a steamVR issue. As they have done a lot of fixes on the newest  version, but thanks to ALVR not working on anything above 2.4.4 yeah.

**Comment by sithlord48** [comment] 2024-05-22 13:41
It seams to be something on the steam side i was able to get this working when i told steam to run steamVR (only tested with 2.4.4) using the [Steam-Play-None](https://github.com/Scrumplex/Steam-Play-None) Compatibility layer.  Using 20.8.1 on both the headset and computer. I used the alvr tarball

**Comment by sanpedrox2** [comment] 2024-05-22 18:12
It works for me if i run vrmonitor.sh from ~/.local/share/Steam/steamapps/common/SteamVR/bin instead of letting alvr launch steamvr

**Comment by 32bitx64bit** [comment] 2024-05-23 15:10
Ok can't get it to launch like at all under wayland.
My guess is its a steamVR wayland issue, as it launched mostly fine under x11.
Beyond annoying as wayland is just superior in most ways *Apart from global hotkeys...*

**Comment by mrnamwen** [comment] 2024-05-23 17:43
Can also confirm that running via vrmonitor.sh allows ALVR to be detected as others have mentioned, but also experiencing #2069 when trying to load the ALVR driver with a headset connected.

**Comment by xDShot** [comment] 2024-05-23 21:08
> > Driver loads, but crashes because of `21:47:05.467632542 ERROR Handshake error for 9643.client: Cannot find audio device which name contains "pipewire"` Then because of the crash the driver gets auto-disabled. Any help?
> 
> If you're still on gnome wayland, gnome wayland does **NOT** support DRM (Direct Rendering Manager) on wayland.
> 
> If this isn't the case revert to the "Previous" version of steamVR, as the driver does not currently support latest steamVR version(s)

It worked before, that's bullshit

**Comment by xDShot** [comment] 2024-05-23 21:20
![Screenshot from 2024-05-24 00-18-48](https://github.com/alvr-org/ALVR/assets/4261659/b95e4c5d-0e66-4b71-85a3-751f64673bfe)

**Comment by zggzcgy** [comment] 2024-05-26 03:08
I'm guessing this might be related to the SteamVR update, and it's recommended to follow [#2115](https://github.com/alvr-org/ALVR/issues/2115#issuecomment-2104671308) to configure it to verify that it's available.

**Comment by 32bitx64bit** [comment] 2024-06-02 03:44
> > > Driver loads, but crashes because of `21:47:05.467632542 ERROR Handshake error for 9643.client: Cannot find audio device which name contains "pipewire"` Then because of the crash the driver gets auto-disabled. Any help?
> > 
> > 
> > If you're still on gnome wayland, gnome wayland does **NOT** support DRM (Direct Rendering Manager) on wayland.
> > If this isn't the case revert to the "Previous" version of steamVR, as the driver does not currently support latest steamVR version(s)
> 
> It worked before, that's bullshit

I should probably clarify. DRM does not work on GNOME on Ubuntu.

**Comment by sithlord48** [comment] 2024-06-25 18:16
I am not using Gnome and have the same issue .  KDE plasma 6.1 seen the issue on both x11  and wayland

**Comment by LordJABA** [comment] 2024-07-11 19:25
Same issue for me, im on KDE plasma 6.1 tried both x11 and wayland
Arch (Garuda)
```
pacman -Si alvr

Repository      : chaotic-aur
Name            : alvr
Version         : 20.8.1-3
Description     : Experimental Linux version of ALVR. Stream VR games from your PC to your headset via Wi-Fi.
Architecture    : x86_64
URL             : https://github.com/alvr-org/ALVR
Licenses        : MIT
Groups          : None
Provides        : alvr
Depends On      : vulkan-icd-loader  libunwind  libdrm  x264  alsa-lib  libva.so=2-64  libva-drm.so=2-64
libva-x11.so  bash  hicolor-icon-theme
Optional Deps   : None
Conflicts With  : alvr
Replaces        : None
Download Size   : 13,99 MiB
Installed Size  : 34,75 MiB
Packager        : Eduard Tolosa <edu4rdshl@protonmail.com>
Build Date      : nie, 2 cze 2024, 16:00:45
Validated By    : SHA-256 Sum
```

**Comment by PugzAreCute** [comment] 2024-07-14 05:31
Same here. 

Arch linux 6.9.7-zen1-1-zen
SteamVR 2.6.2
KDE Plasma 6.1.1 (wayland) 
ALVR streamer v20.9.1 (built from aur package)

**Comment by LordJABA** [comment] 2024-07-14 15:29
adding `vrmonitor.sh %command%` to steamvr custom command was enough for me to get it to work - wont detect driver without it

**Comment by zatricky** [comment] 2024-09-13 22:05
Still an issue ; workarounds required/etc

**Comment by The-personified-devil** [comment] 2024-09-15 00:32
Originally reopened because it seemed like an unrelated issue. The sandboxing issue is tracked by #2242, closing in favor of that.

**Closed by The-personified-devil** 2024-09-15 00:32 UTC
