### ISSUE TITLE
Documentation: Add OVR advanced settings note, patcher note

### ISSUE THREAD

**Issue by Meister1593** [alvr-org/ALVR#2206] opened 2024-06-22 16:32 UTC
OVR Advanced Settings note:
```
## OVR ADVANCED SETTINGS NOTE
Disable driver and don't use it with ALVR.
It's incompatible and will produce ladder-like latency graph with very bad shifting vision
```
Patcher note: (from discord)
```
If you noticed that steamvr can't properly update bindings, open menus, and possibly eats too much cpu, you can apply this patch
https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/blob/main/patch_bindings_spam.sh
It will stop http spam that webserver produces, which stalls it's own chromium frameworks and will reduce cpu load significantly.
One-line installation for default steamvr location:
curl -s https://raw.githubusercontent.com/alvr-org/ALVR-Distrobox-Linux-Guide/main/patch_bindings_spam.sh | sh -s ~/.steam/steam/steamapps/common/SteamVR
```

Note for future development: why OVR and Slimevr breaks this way (find exact cause?)

**Comment by zarik5** [comment] 2024-06-23 09:55
We already know the cause. Because it messes with our pose matching algorithm. Which we've already seen it's wrong. Should be fixed with the tracking rewrite.

**Closed** 2024-07-27 04:05 UTC
Labels: documentation
