### ISSUE TITLE
Error :linking with `link.exe` failed: exit code: 1120

### ISSUE THREAD

**Issue by Hope10086** [alvr-org/ALVR#1255] opened 2022-11-20 06:38 UTC
Hello!

I want to get the screengrab of Texture by using the function: `DirectX::SaveDDSTextureToFile`  provided by [DirectXTex](https://github.com/Microsoft/DirectXTex)  on the vscode . And I add` "ScreenGrab11.h" "ScreenGrab11.cpp"` into  path `alvr\server\cpp\platform\win32 `.    No errors were thrown before  building server. 
Then the following  would be showed in the terminal :

```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "D:\\Microsoft Visual Studio\\2022Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX64\\x64\\link.exe" "/DEF:C:\\Users\\86155\\AppData\\Local\\Temp\\rustclNGQ8k\\lib.def" "/NOLOGO" "C:\\Users\\86155\\AppData\\Local\\Temp\\rustclNGQ8k\\symbols.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.0.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.1.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.10.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.11.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.12.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.13.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.14.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.15.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.2.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.3.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.4.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.5.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.6.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.7.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.8.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.alvr_server.40fb6d5e-cgu.9.rcgu.o" "D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.3a4uusis2af2tx0m.rcgu.o" "/LIBPATH:D:\\AX\\ALVR\\target\\release\\deps" "/LIBPATH:D:\\Microsoft Visual Studio\\2022Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "/LIBPATH:D:\\AX\\ALVR\\target\\release\\build\\alvr_server-3e964d3bcbcc2bcf\\out" "/LIBPATH:D:\\AX\\ALVR\\alvr\\server\\cpp\\openvr/lib" "/LIBPATH:C:\\Users\\86155\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\windows_x86_64_msvc-0.42.0\\lib" "/LIBPATH:D:\\Microsoft Visual Studio\\2022Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "/LIBPATH:D:\\AX\\ALVR\\target\\release\\build\\tinyfiledialogs-0482fee4c478d0f9\\out" "/LIBPATH:D:\\Microsoft Visual Studio\\2022Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "/LIBPATH:D:\\AX\\ALVR\\target\\release\\build\\minimp3-sys-f4558e8f03b4e3f0\\out" "/LIBPATH:D:\\Microsoft Visual Studio\\2022Community\\VC\\Tools\\MSVC\\14.34.31933\\atlmfc\\lib\\x64" "/LIBPATH:D:\\AX\\ALVR\\target\\release\\build\\runas-ca7077a2f0850827\\out" "/LIBPATH:C:\\Users\\86155\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\windows_x86_64_msvc-0.36.1\\lib" "/LIBPATH:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "bindings.lib" "openvr_api.lib" "D:\\AX\\ALVR\\target\\release\\deps\\libreqwest-9718239a16dc7c6b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhyper_tls-b65de0897a75eebc.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libserde_urlencoded-ab1772294d1332b6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwinreg-cacfdd2bb90ac1d1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libipnet-07d95fa36c9ab07a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtokio_native_tls-cb52bd7c62e92732.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnative_tls-5a011b2c46840f5c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libschannel-20e94a61c98ed95a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwindows_sys-0a3beeb69a756a38.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwebbrowser-7ec2dcd37891fa9e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_commands-72025adc4fde120e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librunas-87dfd6359bc8b794.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libencoding_rs_io-54d7791c37887943.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libencoding_rs-ba38cc9c33161184.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libchrono-b748eb6e39808c95.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnum_integer-9c459be79c922d0f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtime-e22dfcd47e85a929.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalcro-4e5f09739815f7e9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libdashmap-a9692ec0f38d1b39.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtinyfiledialogs-57e07a8768e5c37a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblibc-281cbf66fcb0b230.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libos_str_bytes-9d0d8f9897fdefb1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcrossbeam_channel-996e6cbce0dde898.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcrossbeam_utils-25a3a13612663cdf.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtempfile-8317b02490310db2.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfastrand-cdc347dd26b54549.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libremove_dir_all-147edce2bf4fdbe2.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_filesystem-ca69dd6130dffeb4.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libdirs-ee82dc7e47ad83c5.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libdirs_sys-fc24496aef613148.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtokio_tungstenite-c4e6da6d4ea169fe.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtungstenite-219c5a1992ce85cc.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libutf8-489d804e6a5bb320.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsha1-2951881e9d87014d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liburl-42a06015b7f7e86d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libidna-e56d1bd7f53f093d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libunicode_normalization-992a9e4def1d0ae6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libunicode_bidi-04887df29fee7f3c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libform_urlencoded-1c7b4b323ed3daf5.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libpercent_encoding-7750bb07dd161bdd.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhyper-b7992574e298d2b3.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwant-1cedb99db9ae7dbf.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtry_lock-3fd026472181ebb0.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhttparse-faeafd06c55fb271.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libh2-035a13092800f713.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtower_service-0ac25e201efc1463.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhttp_body-90d79c7cf737b57f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libheaders-e7c0973a2d840562.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsha1-637808138e8df360.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcpufeatures-26449582f6c70808.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libdigest-c26ee4638a9edc46.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libblock_buffer-d477212d34ab2940.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcrypto_common-2e9a258b1cb01d48.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgeneric_array-b85cc5d5d4c57f48.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtypenum-aa1090ce751664a0.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libmime-414eab0a6b290936.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhttpdate-8a7ec4b546d65722.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libheaders_core-54e37d4ddaee8271.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhttp-9d4ca00a83a8303f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfnv-a3c774eb62a6305e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbase64-2a630ebbd9ccac65.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfern-919cbd6098d3ab6b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwinit-8c614cfbd9303f56.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwgpu-893a16e58ed60fdb.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwgpu_core-a3bcaa1f9c7c164d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcopyless-01e260c692ea79e1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwgpu_hal-0ec888092c2303b0.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librenderdoc_sys-040cc34db8b3c699.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfxhash-93c0b456b1988513.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgpu_descriptor-bf634a7de96f16f5.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgpu_descriptor_types-eec2762277123fc1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libd3d12-cc2ccbb7c3582d4d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libprofiling-9e0e75202e95cff6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libraw_window_handle-68a15cadb131717b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcty-85519ee205605bf5.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgpu_alloc-b59b7a0ee539a69b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgpu_alloc_types-4c05afec8a574063.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libinplace_it-31e8eecd1a9afbc5.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libash-edced10b13f02805.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblibloading-3c49438a11b712f9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnaga-73f189da74fe9af0.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librustc_hash-240565ab3abf64ef.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcodespan_reporting-8a8dfa4d30c969a9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libunicode_width-39ebe4a836611495.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtermcolor-656bbf9cec39ae3d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwinapi_util-26397c39906fb3fa.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhexf_parse-62260439c9ef95a7.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libspirv-adae557a6233ffe0.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnum_traits-c5c5d520b699000d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libindexmap-1347d3a68ffdb7f4.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhashbrown-1551fb1554d46fc2.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libahash-f63c8c2aa1a14b2c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librange_alloc-dca1510cb2639527.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbit_set-32369cecbd0fdc35.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbit_vec-3b19e2fcb9b2df0d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwgpu_types-3b16fb31502a398f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbitflags-5543560f3fcbe988.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libarrayvec-1ccaea358c6529b9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_audio-bd13b57ed0a4b1bf.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwio-627dbb4ecefffd9c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwidestring-e8aee0ad51e07ed8.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librodio-c4c18848005e9a27.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libhound-9779c67b01dcd791.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblewton-f8aef54450513624.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libogg-6745fd8e3cab9842.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtinyvec-ab72823d0a0c8b7a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtinyvec_macros-14e3c10ca00df0e4.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbyteorder-32370a18bb63cb3c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libminimp3-b8adc93ed9576718.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libslice_deque-38449a7b167ac13c.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libminimp3_sys-c452e8e368bf40ac.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libclaxon-59bf9b322c5e381e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcpal-c53a9104e2996587.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_sockets-1ae03835f9f27bdb.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbincode-60db5f268cccb76f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnonzero_ext-c08a16fb7d2672c9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgovernor-cf8bd22aa6264196.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libquanta-9b2267cde413f160.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libdashmap-33dd4c2e80a963d1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libparking_lot-9d56330541f44312.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libparking_lot_core-d34801783ed38549.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libinstant-60a1a078eaa1f2a1.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_timer-0a0f8853f4ed22c3.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnonzero_ext-5de35263d9943462.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librand-24e9032a6e5d7424.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librand_chacha-3ba8fac0359b3810.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libppv_lite86-92f210b7e997ac38.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librand_core-79d9065d1f01795e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libgetrandom-eaf2b5c160164c57.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libno_std_compat-3a010ef50ee38a85.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtokio_util-76e7233cdad9f55d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtracing-fd01ac07b35aaa99.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtracing_core-a46edaa5a0fb9c02.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libonce_cell-69449b18f63540e6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libtokio-0d9e41ea95753fc6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libnum_cpus-d841ed5da8bbb206.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsocket2-5ca1fb8f061f652f.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libmio-159f9fc633ba58e6.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures-47932f84f20b7651.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_executor-7db74b4b33c3846b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_util-7cbb7a42c02dda70.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libmemchr-b118bc55fe62d9fc.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_io-372b4b830f23c4b3.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libslab-05383bfb79ab081b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_channel-deda4bc0fbdb5b4a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libpin_project_lite-9a2193135a02c137.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_sink-b57b0972d2ca1155.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_task-776e5a00f53ce17b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libpin_utils-c0891aeb56dbc3fd.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libfutures_core-54dfb7e1014fb35b.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbytes-7551405b16850de9.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_session-b370041a2e6eee70.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsettings_schema-51f7378490ce65c7.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libserde_json-dc009305cd506d48.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libryu-81e8492a4baab09e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libitoa-5164f13a70d8e3fb.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbytemuck-8e268ad4eee732bd.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libalvr_common-0dd1de88572d490d.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libmsgbox-9ef9a3f8f82ba8fb.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libwinapi-76846e44de204c0e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libthiserror-77fece365c1473aa.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libbacktrace-5dd688c5ecfee069.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\librustc_demangle-13a5a2010f275622.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsemver-45124b5d81f3a214.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblog-d4acd916e121a499.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblazy_static-542fcc95856a51b3.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libglam-ecf3a96b6dfe9021.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libserde-7f046f18aaf9597a.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libparking_lot-b2b8af54055176af.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libparking_lot_core-a9d1261ce71e6627.rlib" 
"D:\\AX\\ALVR\\target\\release\\deps\\libwindows_sys-da15415b2d0f6ac7.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libcfg_if-183cf413ca209255.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libsmallvec-530a94a4fbd3618e.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\liblock_api-cac473e6f6059a03.rlib" "D:\\AX\\ALVR\\target\\release\\deps\\libscopeguard-8a4daebab7f79b98.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-fdaa63d6970be740.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-a684236a9da37ec6.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-85c151aafb35bf5c.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-7dbe75e48c9029c0.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-78044ac8790346aa.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libminiz_oxide-8743285c70baade8.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libadler-b260ead09cc3ca75.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-200564555b6c364f.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-60e4ae6d068e334f.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-d74559c1731cb9bf.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-3d51e2979c44c27c.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-268ac0a196c81649.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-e74895db82cfb265.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-d805a250e2b7e197.rlib" "C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-3f507ba7adac1c2a.rlib" "windows.lib" "ole32.lib" "user32.lib" "comdlg32.lib" "ole32.lib" "shell32.lib" "shcore.lib" "legacy_stdio_definitions.lib" "bcrypt.lib" "ntdll.lib" "advapi32.lib" "cfgmgr32.lib" "comctl32.lib" "d3d12.lib" "d3dcompiler.lib" "dwmapi.lib" 
"dxgi.lib" "fwpuclnt.lib" "gdi32.lib" "imm32.lib" "kernel32.lib" "mmdevapi.lib" "msimg32.lib" "ntdll.lib" "ole32.lib" "opengl32.lib" "runtimeobject.lib" "shcore.lib" "shell32.lib" "shlwapi.lib" "synchronization.lib" "user32.lib" "uxtheme.lib" "winmm.lib" "winspool.lib" "ws2_32.lib" "windows.lib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.dll" "/OPT:REF,ICF" "/DLL" "/IMPLIB:D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.dll.lib" "/DEBUG" "/NATVIS:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\86155\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: Non-UTF-8 output:   \xd5\xfd\xd4\xda\xb4\xb4\xbd\xa8\xbf\xe2 D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.dll.lib \xba\xcd\xb6\xd4\xcf\xf3 D:\\AX\\ALVR\\target\\release\\deps\\alvr_server.dll.exp\r\nbindings.lib(ScreenGrab11.o) : error 
LNK2019: \xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xb7\xfb\xba\xc5 IID_ID3D11Texture2D\xa3\xac\xba\xaf\xca\xfd \"long __cdecl `anonymous namespace\'::CaptureTexture(struct ID3D11DeviceContext *,struct ID3D11Resource *,struct D3D11_TEXTURE2D_DESC &,class Microsoft::WRL::ComPtr<struct ID3D11Texture2D> &)\" (?CaptureTexture@?A0x4dd09b48@@YAJPEAUID3D11DeviceContext@@PEAUID3D11Resource@@AEAUD3D11_TEXTURE2D_DESC@@AEAV?$ComPtr@UID3D11Texture2D@@@WRL@Microsoft@@@Z) \xd6\xd0\xd2\xfd\xd3\xc3\xc1\xcb\xb8\xc3\xb7\xfb\xba\xc5\r\nD:\\AX\\ALVR\\target\\release\\deps\\alvr_server.dll : fatal error LNK1120: 1 \xb8\xf6\xce\xde\xb7\xa8\xbd\xe2\xce\xf6\xb5\xc4\xcd\xe2\xb2\xbf\xc3\xfc\xc1\xee\r\n

warning: `alvr_server` (lib) generated 4 warnings
error: could not compile `alvr_server` due to previous error; 4 warnings emitted
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StringError("Command failed: ")', alvr\xtask\src\main.rs:209:6
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\std\src\panicking.rs:584
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\panicking.rs:142
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library\core\src\result.rs:1785
   3: enum2$<core::result::Result<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> > >::unwrap<tuple$<>,alloc::boxed::Box<dyn$<core::error::Error>,alloc::alloc::Global> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\result.rs:1107
   4: alvr_xtask::build_server
             at .\alvr\xtask\src\main.rs:202
   5: alvr_xtask::main
             at .\alvr\xtask\src\main.rs:1043
   6: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/897e37553bba8b42751c67658967889d11ecd120\library\core\src\ops\function.rs:248
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\alvr_xtask.exe build-server --release` (exit code: 101)
```
I am new in rust and after  reading some blogs  I beilve  it 's guess  some dependeces hadn't been added into `cargo.toml` 
Is it right? I want to konw what should I do ? Are there any relevant study materials available for reference?

**Comment by zarik5** [comment] 2022-11-20 08:41
Duplicate of #1130

**Closed** 2022-11-20 08:41 UTC
