### ISSUE TITLE
alvr_build_linux.sh all not working 

### ISSUE THREAD

**Issue by schrill** [alvr-org/ALVR#1002] opened 2022-03-08 13:10 UTC
Printed out the value and it seems it tries to create the build_dir named build, but this is a file already been created
Ignored package `cargo-apk v0.8.2` is already installed, use --force to override
"/home/user/built/VR/ALVR/build/temp_download.zip"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 17, kind: AlreadyExists, message: "File exists" }', alvr/xtask/src/command.rs:143:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/result.rs:1065:23
   4: alvr_xtask::command::download_and_extract_zip
             at ./alvr/xtask/src/command.rs:143:5
   5: alvr_xtask::dependencies::get_oculus_openxr_mobile_loader
             at ./alvr/xtask/src/dependencies.rs:163:5
   6: alvr_xtask::dependencies::build_android_deps
             at ./alvr/xtask/src/dependencies.rs:188:5
   7: alvr_xtask::main
             at ./alvr/xtask/src/main.rs:122:33
   8: core::ops::function::FnOnce::call_once
             at /rustc/03918badd33d255de806b4a9a8aa75b031ed0738/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by ryleu** [comment] 2022-05-01 00:45
confirmed on bedrock in a debian stratum when trying to build v18.0.0

**Comment by haydenwalker980** [comment] 2022-08-09 03:13
Creating the directory manually works to solve this issue for now. This should be fixed though

**Comment by Vixea** [comment] 2023-07-03 03:36
Outdated because it's been removed

**Closed** 2023-07-03 03:36 UTC
Labels: bug, linux, packaging
