### ISSUE TITLE
ALVR addon doesn't appear on Steamvr

### ISSUE THREAD

**Issue by KuraakaiGoro** [alvr-org/ALVR#2112] opened 2024-05-08 02:54 UTC
![ALVR issue](https://github.com/alvr-org/ALVR/assets/88090640/ddcaccf6-e7db-452e-8c42-e441fc8c3480)
## Description
I had a problem launching Steamvr, and had to reinstall Steam to get it to work. Then when I launched ALVR, the plugin no longer appeared. I tried reinstalling steamvr, and ALVR to no avail. I registered the plugin, at /usr/lib/steamvr/alvr so idk what's wrong

## General Troubleshooting
- [X] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [X] I read the ALVR Wikis [polygraphene's ALVR GitHub Wiki](https://github.com/polygraphene/ALVR/wiki) and [ALVR GitHub Wiki](https://github.com/alvr-org/ALVR/wiki)

### Hardware
**Note**: for Linux, an upload to the [`hw-probe`](https://linux-hardware.org/) database is preferred: `hw-probe -all -upload`

**CPU**: 
Ryzen 5 5600x

**GPU**: 
Nvidia RTX 3070ti

**GPU Driver Version**: 
nvidia-550

**Audio**: 
Pulse Audio, Pipewire

### Installation
**ALVR Version**: 
alvr-nvidia 20.7.1-1

**ALVR Settings File**:

**SteamVR Version**: 
2.5.4

**Install Type**:
- [X] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
EndeavourOS 24.5.8-1 with Plasmashell 6.0.4

**Comment by ymndoseijin** [comment] 2024-05-08 03:03
I might have had a similar problem with the new SteamVR update, something happened that caused SteamVR to send `no steam runtime environment set, please use sniper SLR` to stdout and then crash, I had to reinstall Steam to get it working back, but then ALVR didn't seem to be working at all on the newest version. Maybe try running the previous release branch? That's what I'm currently doing.

**Comment by KuraakaiGoro** [comment] 2024-05-08 03:08
> I might have had a similar problem with the new SteamVR update, something happened that caused SteamVR to send `no steam runtime environment set, please use sniper SLR` to stdout and then crash, I had to reinstall Steam to get it working back, but then ALVR didn't seem to be working at all on the newest version. Maybe try running the previous release branch as a workaround? That's what I'm currently doing.

That works. Should I keep this issue open until a permanent fix is found?

**Comment by ymndoseijin** [comment] 2024-05-08 03:12
I guess so, as it's a problem on the main SteamVR branch

**Comment by GrigoriyPeters** [comment] 2024-05-15 14:23
Welp. Now even the 'previous' beta branch (2.4.4) of SteamVR doesn't work for me.
SteamVR just won't register the ALVR driver.

**Comment by infidelus** [comment] 2024-05-15 17:21
> Welp. Now even the 'previous' beta branch (2.4.4) of SteamVR doesn't work for me. SteamVR just won't register the ALVR driver.

Yep, been seeing this since yesterday evening when I tried to use ALVR.  Not sure what's changed though.

**Comment by infidelus** [comment] 2024-05-15 20:29
Well I'm on 20.8.1 so unless I go to nightly releases (which seem to not always be nightly) there's nothing for me to upgrade to.  It's not blocked.

**Comment by KuraakaiGoro** [comment] 2024-05-15 22:54
strange, I'm using the Nvidia fork on Linux if that adds any context

**Comment by infidelus** [comment] 2024-05-16 14:24
Well, no idea what's wrong with it.  Completely uninstalled & reinstalled Steam then SteamVR, ran SteamVR and closed it.  Ran ALVR and it's still not showing the alvr_server add-on in SteamVR settings and it just tells me to plug my headset in now.  Even tried the latest nightly.

**Comment by infidelus** [comment] 2024-05-16 15:38
OK, I have finally got ALVR working (at least back into the SteamVR home screen) by following the instructions at https://github.com/Scrumplex/Steam-Play-None.

Note however that that Proton-Up-Qt did not work in x11 as it complained about no QT environment.  Fortunately Linux Mint recently added Wayland support so once I logged back in on that I could run it, then log back into x11 and follow the rest of the instructions.

**Comment by mohammad-matini** [comment] 2024-05-16 16:18
Had black screens on SteamVR 2.4.4 yesterday, also fixed by using https://github.com/Scrumplex/Steam-Play-None. The SteamVR container runtime issues may also be related to the x264 linking issue mentioned on https://github.com/alvr-org/ALVR/issues/2130.

**Comment by GrigoriyPeters** [comment] 2024-05-17 17:08
> OK, I have finally got ALVR working (at least back into the SteamVR home screen) by following the instructions at https://github.com/Scrumplex/Steam-Play-None.
> 
> Note however that that Proton-Up-Qt did not work in x11 as it complained about no QT environment. Fortunately Linux Mint recently added experimental Wayland support so once I logged back in on that I could run it, then log back into x11 and follow the rest of the instructions.

Thanks! Now ALVR 20.8.1 works with SteamVR 2.4.4 for me.

**Comment by zggzcgy** [comment] 2024-05-26 03:03
I'm guessing this might be related to the SteamVR update, and it's recommended to follow [#2115](https://github.com/alvr-org/ALVR/issues/2115#issuecomment-2104671308) to configure it to verify that it's available.

**Comment by The-personified-devil** [comment] 2024-06-13 16:56
There's a better workaround, see the [linux troubleshooting page of the wiki](https://github.com/alvr-org/ALVR/wiki/Linux-Troubleshooting)

**Comment by Vixea** [comment] 2024-06-15 15:50
Closing as duplicate of other issues

**Closed by Vixea** 2024-06-15 15:50 UTC
