### ISSUE TITLE
Stationary Guardian causes jitter on AMD.

### ISSUE THREAD

**Issue by andy-d1969** [alvr-org/ALVR#708] opened 2021-06-24 07:31 UTC
Roomscale Guardian is smooth. Until 8146ff1c it was the other way around.
Hope there is an easy way to fix the jitter for stationary Guardian setups.

**Comment by Espionage724** [comment] 2021-08-16 03:36
Could you please clarify this more? How do you switch between Stationary and Roomscale guardians? Do you need to set-up a Guardian through SteamVR at all?

**Comment by zarik5** [comment] 2022-02-28 13:11
The playspace sync has been rewritten. It is not the cause of the jitter. This is a problem at SteamVR level, which will be fixed upstream.

**Closed by zarik5** 2022-02-28 13:11 UTC
Labels: bug, linux
