### ISSUE TITLE
Quest 2 thumb rest sensors don't do anything

### ISSUE THREAD

**Issue by art0007i** [alvr-org/ALVR#591] opened 2021-04-11 16:58 UTC
It would be nice to have them work

**Comment by zarik5** [comment] 2021-04-11 17:54
This is planned. Currently we are using an older SDK to support the Oculus Go (so the thumb rest is not supported), but this will change after we switch to OpenXR.

**Comment by ronthecookie** [comment] 2021-05-17 18:33
Duplicate of #255.

**Closed** 2021-06-23 21:02 UTC
Labels: duplicate, wontfix

**Comment by ckiee** [comment] 2021-07-17 18:42
(This shouldn't have been auto-closed.)
