### ISSUE TITLE
(Duplicate) Black Screen in headset

### ISSUE THREAD

**Issue by jurassicjordan** [alvr-org/ALVR#2191] opened 2024-06-14 21:05 UTC
## Description
As of June 12, 2024 the "previous" workaround, for this problem is now borked. Steam has pushed the 2.6 update for steam vr, pushing 2.5.5 into the previous slot for now. 
## Environment
Operating System: EndeavourOS 
KDE Plasma Version: 6.0.5
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.9.3-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10700K CPU @ 3.80GHz
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2

additional hardware information is available here 
https://linux-hardware.org/?probe=d9f4927a1a

### Installation
**ALVR Version**:
20.8.1
**ALVR Settings File**:

**SteamVR Version**:

**Install Type**:
- [  ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ X] Portable (`zip`)
- [  ] Source

**Comment by Vixea** [comment] 2024-06-15 15:48
Closing as duplicate of #2190

**Closed by Vixea** 2024-06-15 15:48 UTC
