### ISSUE TITLE
Launcher stuck minimised 

### ISSUE THREAD

**Issue by theprisoner666** [alvr-org/ALVR#508] opened 2021-02-28 15:37 UTC
# Please follow the general troubleshooting steps first:

- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and completed successfully the setup wizard.
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

If your issue is about games not working, please open an issue for every game and list the game in the title.

### Bug reports:

Whenever I start the ALVR launcher it starts SteamVR ok, but the ALVR launcher window is constantly minimised to the task bar, and clicking on it doesn’t maximise it. I always need to hover my cursor over the task bar icon, right click, then select ‘maximise’ to see launcher window.

It’s not a major issue, but it would be nice if it was fixed. 

Thanks.

#### Environement

Windows 10, RTX 3070, ALVR 15.0.0. 

### Features:

**Please note by far the quickest way to get a new feature is to file a Pull Request.**

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by zarik5** [comment] 2021-02-28 18:13
Are you using Chrome or Edge?

**Comment by zarik5** [comment] 2021-02-28 19:18
Maybe I know what is going on. Are you using multiple displays (or virtual displays)?

**Comment by theprisoner666** [comment] 2021-02-28 22:49
I use Chrome. Yes, it does have a similar issue where the window would be on another display, but I checked both displays and it doesn’t appear on either of them. I will try disconnecting one display later tonight to see if this helps.

Thanks.

**Comment by mikeandlina** [comment] 2021-03-04 01:11
I have the same problem. No issues with v14.
Win 10 (Version 10.0.19042 Build 19042)
GTX 1060
ALVR 15
Chrome Version 89.0.4389.72 (Official Build) (64-bit)
single hdmi connected display

Clever bit with the hover/maximize, I reverted to v14 because I thought it had simply crashed, but now I have access to the interface and it is working fine with 60ms latency (30 ms other?).

**Comment by eximer168** [comment] 2021-03-31 04:50
> I have the same problem. No issues with v14.
> Win 10 (Version 10.0.19042 Build 19042)
> GTX 1060
> ALVR 15
> Chrome Version 89.0.4389.72 (Official Build) (64-bit)
> single hdmi connected display
> 
> Clever bit with the hover/maximize, I reverted to v14 because I thought it had simply crashed, but now I have access to the interface and it is working fine with 60ms latency (30 ms other?).

Same problem occurs across Dell XPS/15 as well as Generic Windows 10/PC.
The issue isn't central to the browser/Chrome, but rather what happens when ALVR (the app) starts.
The window pops-down and refuses to resize/maximize -- if it occur before you run the wizard (always the case), there is no way to use the App.

v14 does work very well once set up, upgrading to 15 causes the minimization problem.
workaround: At startup the app detects and asks upgrade, select dismiss and the app works nominally under v14.

**Comment by eximer168** [comment] 2021-04-04 14:55
SOLUTION!   Turn resolution down on the monitor below the recommended 3840x1260 to something smaller, 1900x1200.
Works every time w/15.1. 

High praise for the technical achievement of ALVR  
Theory: Believe this to be a smartTV/windows problem, is it possible the window creation call was different in 14.x?  
perhaps ALVR window not getting a valid window size due resolution negotiation if not pinned at something specific.

**Comment by zarik5** [comment] 2021-04-10 13:58
This should be fixed in v15.1.2

**Closed by zarik5** 2021-04-10 13:58 UTC
